sonar.projectKey=Jovandosg_Encontro-DevOps-Custom
sonar.organization=jovandosg

# Informações do projeto
sonar.projectName=Encontros DevOps
sonar.projectVersion=1.0

# Fontes e exclusões
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,aks-iac/**,static/**,templates/**
sonar.tests=tests/

# Cobertura de código Python (gerado pelo pytest --cov-report=xml)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

# Encoding
sonar.sourceEncoding=UTF-8
